version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
    commands:
      - npm install -g aws-cdk
      - pip3 install -r requirements.txt
  build:
    commands:
      - cdk synth
