[tool.black]
line-length = 88
target-version = ['py37']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | \.idea
  | build
  | dist
  | cdk.out
)/
'''

[tool.isort]
profile = 'black'
line_length = 88
force_single_line = true
